import type { Issue, Suggestion } from "../../../shared/types"
import { useActivePlan, useStore } from "../store"
import { termName } from "../lib/derive"
import { useReport } from "./Board"

function IssueItem({ i }: { i: Issue }) {
  const select = useStore(s => s.selectCourse)
  const dag = useStore(s => s.dag)!
  // engine labels "Fall Year 2" -> board names "Fall 2027"
  const msg = i.message.replace(/(Fall|Spring) Year (\d)/g, (_m, season: string, y: string) => termName(dag, (Number(y) - 1) * 2 + (season === "Fall" ? 1 : 2)))
  return (
    <li className="cursor-pointer rounded border border-white/10 bg-white/[0.03] p-2 hover:border-slate-600" onClick={() => i.courseIds[0] && select(i.courseIds[0])}>
      <div><span className="mr-1 font-mono text-[10px] text-slate-500">{i.code}</span>{msg}</div>
      {i.quote && <div className="mt-1 text-[11px] italic text-slate-400">Bulletin: "{i.quote.slice(0, 220)}"</div>}
      {i.sourceUrl && <a className="text-[11px] text-sky-300 underline" href={i.sourceUrl} target="_blank" rel="noreferrer" onClick={e => e.stopPropagation()}>Source</a>}
    </li>
  )
}

export function EvaluatePanel() {
  const report = useReport()
  const ev = useStore(s => s.evaluation)
  const plan = useActivePlan()
  const st = useStore.getState()
  if (!report) return null
  const by = (sev: Issue["severity"]) => report.issues.filter(i => i.severity === sev)
  const errors = by("error"), warnings = by("warning").filter(i => i.code !== "REQ_GROUP_INCOMPLETE"), infos = by("info")
  const missing = report.requirementStatus.filter(r => !r.satisfied)
  const verdict = errors.length ? { t: `Fix ${errors.length} error${errors.length > 1 ? "s" : ""} first`, c: "bg-red-700" }
    : report.graduationReady ? { t: "Valid plan: graduation-ready", c: "bg-emerald-700" } : { t: "Valid but incomplete", c: "bg-amber-700" }
  const apply = (s: Suggestion) => {
    if (s.remove) st.unplaceCourse(s.remove)
    st.moveCourse(s.add, s.semester)
  }
  const Tag = ({ ai }: { ai?: boolean }) => <span className={`ml-2 rounded px-1.5 py-0.5 text-[10px] font-normal normal-case ${ai ? "bg-violet-800 text-violet-100" : "bg-slate-700 text-slate-200"}`}>{ai ? "Generated by Gemini" : "Checked by rules engine"}</span>
  const H = ({ children, ai }: { children: React.ReactNode; ai?: boolean }) => <div className="mb-1 mt-4 text-xs font-semibold uppercase tracking-wide text-slate-400">{children}<Tag ai={ai} /></div>

  return (
    <aside className="w-[400px] shrink-0 overflow-y-auto border-l border-white/10 bg-black p-4 text-sm text-slate-200">
      <div className="flex items-center justify-between"><div className="text-base font-semibold">Evaluate: {plan.name}</div>
        <button className="text-slate-400 hover:text-white" onClick={() => st.setPanel("none")}>✕</button></div>
      <div className={`mt-3 rounded-md px-3 py-2 font-semibold text-white ${verdict.c}`}>{verdict.t} · {report.totalUnitsPlanned} units</div>
      {errors.length > 0 && <><H>Errors</H><ul className="space-y-1">{errors.map(i => <IssueItem key={i.id} i={i} />)}</ul></>}
      {warnings.length > 0 && <><H>Warnings</H><ul className="space-y-1">{warnings.map(i => <IssueItem key={i.id} i={i} />)}</ul></>}
      {missing.length > 0 && <><H>Missing requirements</H><ul className="space-y-1">{missing.map(r => (
        <li key={r.groupId} className="rounded border border-white/10 bg-white/[0.03] p-2"><b>{r.title}</b>: {r.unitsNeed != null ? `${r.unitsHave} of ${r.unitsNeed} units` : r.missingCourseIds.join(", ")}</li>))}</ul></>}
      {!ev && <div className="mt-4 animate-pulse text-xs text-slate-400">Waiting for the career analysis…</div>}
      {ev && <>
        <H>Career direction (scores by code)</H>
        <div className="space-y-1">{ev.directionScores.map(d => (
          <div key={d.directionId} className="flex items-center gap-2 text-xs"><span className="w-32 truncate">{d.label}</span>
            <div className="h-2 flex-1 rounded bg-white/10"><div className="h-2 rounded bg-sf-gold" style={{ width: `${d.score}%` }} /></div><span className="w-8 text-right">{d.score}</span></div>))}</div>
        {ev.ai ? <>
          <H ai>Explanation</H>
          <p>{ev.ai.summary}</p><p className="mt-2">{ev.ai.directionExplanation}</p>
          <H ai>Suggestions (each re-checked by the engine)</H>
          {ev.ai.suggestions.length === 0 && <div className="text-xs text-slate-400">No suggestions passed the engine.</div>}
          <ul className="space-y-1">{ev.ai.suggestions.map((s, k) => (
            <li key={k} className="rounded border border-violet-900 bg-violet-950/40 p-2">
              <div className="font-mono text-xs">{s.remove ? `${s.remove} → ` : "+ "}{s.add} (semester {s.semester})</div>
              <div className="text-xs text-slate-300">{s.reason}</div>
              <button className="mt-1 rounded bg-violet-700 px-2 py-0.5 text-xs" onClick={() => apply(s)}>Apply</button>
            </li>))}</ul>
          {ev.droppedSuggestions > 0 && <div className="mt-1 text-xs text-amber-300">{ev.droppedSuggestions} Gemini suggestion(s) dropped: they broke a rule or named an unknown course.</div>}
        </> : <div className="mt-4 text-xs text-amber-300">Gemini explanation unavailable ({ev.aiStatus}). Engine results above are complete.</div>}
      </>}
      {infos.length > 0 && <><H>Info</H><ul className="space-y-1 text-xs text-slate-400">{infos.map(i => <li key={i.id}>{i.message}</li>)}</ul></>}
      <div className="mt-6 border-t border-white/10 pt-3 text-xs text-slate-500">Always confirm with your SFSU advisor. This planner does not check GE areas, SF State Studies or the 30 upper-division-unit rule.</div>
    </aside>
  )
}
