"""Generate web/data.js (DAG + compact catalog + sample transcript) for the planner UI.

Usage: python3 web/make_data.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data", "sfsu")

# Illustrative transcript in the shape a transcript-extraction step (e.g. an LLM reading a PDF)
# should return. Not a real student.
SAMPLE = {
    "student": "Sample student",
    "source": "Sample transcript (demo data)",
    "current_term": {"season": "Fall", "year": 2026},
    "placement": {"calculus": True},
    "courses": [
        {"code": "CSC 101", "grade": "A", "units": 3, "term": "Fall 2024", "confidence": 0.99},
        {"code": "MATH 226", "grade": "B", "units": 4, "term": "Fall 2024", "confidence": 0.98},
        {"code": "ENG 114", "grade": "A-", "units": 3, "term": "Fall 2024", "confidence": 0.97},
        {"code": "COMM 150", "grade": "B+", "units": 3, "term": "Fall 2024", "confidence": 0.96},
        {"code": "AFRS 101", "grade": "A", "units": 3, "term": "Fall 2024", "confidence": 0.97},
        {"code": "CSC 215", "grade": "B+", "units": 4, "term": "Spring 2025", "confidence": 0.98},
        {"code": "MATH 227", "grade": "C+", "units": 4, "term": "Spring 2025", "confidence": 0.62},
        {"code": "HIST 101", "grade": "B", "units": 3, "term": "Spring 2025", "confidence": 0.95},
        {"code": "ARTH 201", "grade": "A-", "units": 3, "term": "Spring 2025", "confidence": 0.94},
        {"code": "CIS 22A", "grade": "A", "units": 3, "term": "Summer 2025 (transfer)", "confidence": 0.9},
        {"code": "CSC 220", "grade": "B", "units": 3, "term": "Fall 2025", "confidence": 0.99},
        {"code": "CSC 230", "grade": "B-", "units": 3, "term": "Fall 2025", "confidence": 0.97},
        {"code": "PHYS 220", "grade": "B", "units": 3, "term": "Fall 2025", "confidence": 0.98},
        {"code": "PHYS 222", "grade": "A", "units": 1, "term": "Fall 2025", "confidence": 0.98},
        {"code": "BIOL 100", "grade": "A", "units": 3, "term": "Fall 2025", "confidence": 0.96},
        {"code": "AA S 106", "grade": "A", "units": 3, "term": "Fall 2025", "confidence": 0.93},
        {"code": "MATH 225", "grade": "A-", "units": 3, "term": "Spring 2026", "confidence": 0.98},
        {"code": "AA S 216", "grade": "B+", "units": 3, "term": "Spring 2026", "confidence": 0.95},
        {"code": "AFRS 203", "grade": "B", "units": 3, "term": "Spring 2026", "confidence": 0.95},
        {"code": "ANTH 110", "grade": "A", "units": 3, "term": "Spring 2026", "confidence": 0.94},
        {"code": "CSC 256", "grade": "IP", "units": 3, "term": "Fall 2026", "confidence": 0.99},
        {"code": "CSC 317", "grade": "IP", "units": 3, "term": "Fall 2026", "confidence": 0.99},
        {"code": "MATH 324", "grade": "IP", "units": 3, "term": "Fall 2026", "confidence": 0.98},
        {"code": "PHYS 230", "grade": "IP", "units": 3, "term": "Fall 2026", "confidence": 0.98},
        {"code": "PHYS 232", "grade": "IP", "units": 1, "term": "Fall 2026", "confidence": 0.97},
        {"code": "ENG 214", "grade": "IP", "units": 3, "term": "Fall 2026", "confidence": 0.96},
    ],
}


def main():
    dag = json.load(open(os.path.join(DATA, "dags", "bs-computer-science.json")))
    courses = json.load(open(os.path.join(DATA, "courses.json")))
    catalog = {c["code"]: [c["title"], c["units"]] for c in courses}
    for row in SAMPLE["courses"]:
        if row["code"] != "CIS 22A":
            assert row["code"] in catalog, row["code"]
    with open(os.path.join(HERE, "data.js"), "w") as f:
        f.write("// Generated by web/make_data.py from data/sfsu. Do not edit by hand.\n")
        f.write("window.DAG = " + json.dumps(dag, ensure_ascii=False, separators=(",", ":")) + ";\n")
        f.write("window.CATALOG = " + json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + ";\n")
        f.write("window.SAMPLE_TRANSCRIPT = " + json.dumps(SAMPLE, ensure_ascii=False, indent=1) + ";\n")
    print("wrote web/data.js", os.path.getsize(os.path.join(HERE, "data.js")) // 1024, "KB")


if __name__ == "__main__":
    main()
